import connectdb from "~~/lib/db";
import PlayerUsernames from "~~/lib/models/PlayerUsernames";

const adjectives = [
  "Happy",
  "Sad",
  "Fast",
  "Slow",
  "Red",
  "Blue",
  "Quiet",
  "Loud",
  "Brave",
  "Calm",
  "Angry",
  "Bitter",
  "Bright",
  "Dark",
  "Dizzy",
  "Gentle",
  "Graceful",
  "Greedy",
  "Harsh",
  "Jolly",
  "Lazy",
  "Lively",
  "Lonely",
  "Luminous",
  "Mysterious",
  "Nervous",
  "Optimistic",
  "Patient",
  "Playful",
  "Powerful",
  "Radiant",
  "Restless",
  "Shiny",
  "Silent",
  "Smart",
  "Sneaky",
  "Strong",
  "Tender",
  "Tough",
  "Vibrant",
  "Vigilant",
  "Wild",
  "Wise",
  "Witty",
  "Zany",
  "Aggressive",
  "Bold",
  "Clever",
  "Clumsy",
  "Confident",
  "Creative",
  "Curious",
  "Daring",
  "Defiant",
  "Determined",
  "Devoted",
  "Elegant",
  "Energetic",
  "Fearless",
  "Friendly",
  "Generous",
  "Glorious",
  "Grumpy",
  "Hasty",
  "Heroic",
  "Impatient",
  "Impressive",
  "Impulsive",
  "Inquisitive",
  "Intense",
  "Jovial",
  "Kind",
  "Loyal",
  "Majestic",
  "Mighty",
  "Naive",
  "Noble",
  "Obedient",
  "Outgoing",
  "Passionate",
  "Persuasive",
  "Proud",
  "Reckless",
  "Rebellious",
  "Reliable",
  "Resilient",
  "Rough",
  "Ruthless",
  "Savage",
  "Sincere",
  "Sly",
  "Sophisticated",
  "Spirited",
  "Steady",
  "Stubborn",
  "Tactful",
  "Tenacious",
  "Trustworthy",
  "Vain",
  "Valiant",
  "Whimsical",
];

const nouns = [
  "Tiger",
  "Mountain",
  "River",
  "Sky",
  "Lion",
  "Wolf",
  "Eagle",
  "Fox",
  "Dragon",
  "Phoenix",
  "Tree",
  "Ocean",
  "Bridge",
  "Storm",
  "Desert",
  "Forest",
  "Valley",
  "Galaxy",
  "Star",
  "Planet",
  "Island",
  "Canyon",
  "Waterfall",
  "Lake",
  "Meadow",
  "Cliff",
  "Volcano",
  "Skyline",
  "Fortress",
  "Palace",
  "Temple",
  "Pyramid",
  "Garden",
  "Jungle",
  "Tower",
  "Village",
  "City",
  "Cottage",
  "Cave",
  "Mine",
  "Labyrinth",
  "Ship",
  "Submarine",
  "Car",
  "Train",
  "Bicycle",
  "Airplane",
  "Rocket",
  "Spaceship",
  "Library",
  "Museum",
  "Theater",
  "Market",
  "Bakery",
  "Workshop",
  "Factory",
  "Shop",
  "Court",
  "Arena",
  "Stadium",
  "Cathedral",
  "Church",
  "Mosque",
  "Synagogue",
  "Campfire",
  "Lantern",
  "Lamp",
  "Chandelier",
  "Fountain",
  "Clock",
  "Compass",
  "Map",
  "Book",
  "Scroll",
  "Painting",
  "Statue",
  "Sword",
  "Shield",
  "Crown",
  "Throne",
  "Goblet",
  "Mirror",
  "Telescope",
  "Camera",
  "Microphone",
  "Piano",
  "Guitar",
  "Drum",
  "Violin",
  "Flute",
  "Harp",
  "Computer",
  "Robot",
  "Drone",
  "Helicopter",
  "Satellite",
  "Meteor",
  "Comet",
  "Asteroid",
  "Boulder",
  "Pebble",
  "Bear",
  "Hawk",
  "Horse",
  "Whale",
  "Shark",
  "Stallion",
  "Elephant",
  "Rhino",
  "Dolphin",
  "Falcon",
  "Panther",
  "Cheetah",
  "Jaguar",
  "Cougar",
  "Leopard",
  "Zebra",
  "Giraffe",
  "Buffalo",
  "Antelope",
  "Camel",
  "Coyote",
  "Otter",
  "Walrus",
  "Penguin",
  "Crocodile",
  "Turtle",
  "Octopus",
  "Squid",
  "Jellyfish",
  "Salmon",
  "Parrot",
  "Seagull",
  "Owl",
  "Hummingbird",
  "Woodpecker",
  "Hedgehog",
  "Rabbit",
  "Squirrel",
  "Skunk",
  "Raccoon",
  "Lynx",
  "Beetle",
  "Butterfly",
  "Dragonfly",
  "Scorpion",
  "Lobster",
  "Crab",
  "Starfish",
  "Peacock",
  "Bat",
  "Frog",
  "Toad",
  "Snake",
  "Lizard",
  "Iguana",
  "Chameleon",
  "Puma",
  "Bison",
  "Hyena",
  "Jackal",
  "Wolverine",
  "Gazelle",
  "Gorilla",
  "Chimpanzee",
  "Orangutan",
  "Koala",
  "Kangaroo",
  "Wallaby",
  "Platypus",
  "Armadillo",
  "Guanaco",
  "Vulture",
  "Heron",
  "Pelican",
  "Flamingo",
  "Swan",
  "Pigeon",
  "Crow",
  "Raven",
  "Magpie",
  "Rook",
  "Porcupine",
  "Mongoose",
  "Meerkat",
  "Badger",
  "Foxhound",
  "Collie",
  "Wolfhound",
  "Bulldog",
  "Poodle",
  "Chihuahua",
  "Beagle",
  "Retriever",
  "Mastiff",
];

const getRandomNumber = (min: number, max: number): number => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

const generateUsername = (): string => {
  const randomAdjective = adjectives[getRandomNumber(0, adjectives.length - 1)];
  const randomNoun = nouns[getRandomNumber(0, nouns.length - 1)];
  // const randomNumber = getRandomNumber(1000, 9999);
  return `${randomAdjective}${randomNoun}`;
};

export const usernameExists = async (username: string): Promise<boolean> => {
  const existingUser = await PlayerUsernames.findOne({ username }).exec();
  return existingUser !== null;
};

export const generateUniqueUsername = async (): Promise<string> => {
  let username = generateUsername();

  while (await usernameExists(username)) {
    username = generateUsername();
  }

  return username;
};

export const fetchOrCreateUsername = async (address: string): Promise<string> => {
  try {
    await connectdb();

    let player = await PlayerUsernames.findOne({ address }).exec();

    if (player) {
      return player.username;
    }

    const generatedUsername = await generateUsername();

    player = new PlayerUsernames({ address, username: generatedUsername });
    await player.save();

    return generatedUsername;
  } catch (error) {
    throw new Error("Error fetching or creating username: " + (error as Error).message);
  }
};
